(function(){
  "use strict";
  const QUESTIONS=window.GEOGRAPHY_QUESTIONS||[];
  const STORAGE_KEY="social-quiz-progress-v1",SETTINGS_KEY="social-quiz-settings-v1",MASTERY_KEY="social-quiz-mastery-v1";
  const SCOPE_LABELS={first:"小4前期",summer:"夏期講習",all:"全範囲"},TYPE_LABELS={choice:"4択",written:"記述"};
  const UNIT_TITLES={1:"くらしの開拓者",2:"都市と郷土の覇者",3:"地図記号の覇者",4:"方位と縮尺の覇者",5:"日本列島の覇者",6:"世界の中の日本の覇者",7:"時差の覇者",8:"四十七都道府県の覇者",9:"気候の覇者",10:"南国の覇者",11:"北の大地の覇者",12:"雪国の覇者",13:"低地の覇者",14:"海辺の覇者",15:"盆地の覇者",16:"高原の覇者",17:"国土の覇者"};
  const SUMMER_TITLES={"北海道・東北":"北国の覇者","関東":"東国の覇者","中部":"日本の屋根の覇者","近畿":"古都の覇者","中国":"山陰山陽の覇者","四国":"四国の覇者","九州・沖縄":"南海の覇者"};
  const RANKS=[{count:0,name:"はじまりの旅人",emblem:"🧭"},{count:1,name:"知識の冒険者",emblem:"⚔️"},{count:3,name:"列島の探索者",emblem:"🗺️"},{count:5,name:"地理の戦士",emblem:"🛡️"},{count:10,name:"国土の賢者",emblem:"📜"},{count:15,name:"日本列島の覇者",emblem:"👑"},{count:17,name:"黄金の国土王",emblem:"🏆"}];
  const UNIT_META=[...new Map(QUESTIONS.filter(q=>q.source==="小4前期").map(q=>[q.unit,{unit:q.unit,name:q.unitName||`単元${q.unit}`}])).values()].sort((a,b)=>a.unit-b.unit),ALL_UNITS=UNIT_META.map(x=>x.unit),SUMMER_REGIONS=Object.keys(SUMMER_TITLES);
  const screens={home:document.getElementById("home-screen"),quiz:document.getElementById("quiz-screen"),result:document.getElementById("result-screen")},$=id=>document.getElementById(id);
  const state={sessionMode:"main",quizType:"choice",scope:"first",selectedUnits:[],selectedSummerRegions:[],deck:[],index:0,score:0,answers:[],startedAt:0,mainResult:null,masteryTarget:null,achievementEvents:[]};
  function shuffle(values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function localDateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
  function loadProgress(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return v&&Array.isArray(v.history)?v:{version:1,history:[]}}catch{return{version:1,history:[]}}}
  function saveProgress(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
  function loadSettings(){try{const v=JSON.parse(localStorage.getItem(SETTINGS_KEY));const selectedUnits=Array.isArray(v?.selectedUnits)?[...new Set(v.selectedUnits.filter(x=>ALL_UNITS.includes(x)))].sort((a,b)=>a-b):[...ALL_UNITS],selectedSummerRegions=Array.isArray(v?.selectedSummerRegions)?SUMMER_REGIONS.filter(x=>v.selectedSummerRegions.includes(x)):[...SUMMER_REGIONS];return{soundEnabled:v?.soundEnabled!==false,soundVolume:Number.isFinite(v?.soundVolume)?Math.max(0,Math.min(1,v.soundVolume)):0.7,lastScope:SCOPE_LABELS[v?.lastScope]?v.lastScope:"first",lastQuizType:TYPE_LABELS[v?.lastQuizType]?v.lastQuizType:"choice",selectedUnits,selectedSummerRegions}}catch{return{soundEnabled:true,soundVolume:0.7,lastScope:"first",lastQuizType:"choice",selectedUnits:[...ALL_UNITS],selectedSummerRegions:[...SUMMER_REGIONS]}}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function emptyMastery(){return{version:1,units:{},summerRegions:{}}}
  function loadMastery(){try{const v=JSON.parse(localStorage.getItem(MASTERY_KEY));if(!v||!v.units||typeof v.units!=="object")return emptyMastery();if(!v.summerRegions||typeof v.summerRegions!=="object")v.summerRegions={};return v}catch{return emptyMastery()}}
  function saveMastery(v){localStorage.setItem(MASTERY_KEY,JSON.stringify(v))}
  function unitRecord(mastery,unit){return mastery.units[String(unit)]||{choiceBest:0,choiceTotal:0,choiceBestRate:0,writtenBest:0,writtenTotal:0,writtenBestRate:0,choiceAttempts:0,writtenAttempts:0,choiceMastered:false,writtenMastered:false}}
  function summerRecord(mastery,region){return mastery.summerRegions[region]||{choiceBest:0,choiceTotal:0,choiceBestRate:0,writtenBest:0,writtenTotal:0,writtenBestRate:0,choiceAttempts:0,writtenAttempts:0,choiceMastered:false,writtenMastered:false}}
  const settings=loadSettings();state.scope=settings.lastScope;state.quizType=settings.lastQuizType;state.selectedUnits=[...settings.selectedUnits];state.selectedSummerRegions=[...settings.selectedSummerRegions];
  const AUDIO_REVISION="20260815-v9-9",sounds={correct:new Audio(`./se-correct.mp3?v=${AUDIO_REVISION}`),wrong:new Audio(`./se-wrong.mp3?v=${AUDIO_REVISION}`)};Object.values(sounds).forEach(x=>x.preload="auto");
  function playSound(correct){if(!settings.soundEnabled||settings.soundVolume<=0)return;const x=correct?sounds.correct:sounds.wrong;x.pause();x.currentTime=0;x.volume=settings.soundVolume;const p=x.play();if(p?.catch)p.catch(()=>{})}
  function renderSoundSettings(){$("sound-enabled").checked=settings.soundEnabled;$("sound-enabled").nextElementSibling.textContent=settings.soundEnabled?"効果音 ON":"効果音 OFF";$("sound-volume").value=Math.round(settings.soundVolume*100);$("sound-volume-value").textContent=`${Math.round(settings.soundVolume*100)}%`}
  function showScreen(name){Object.entries(screens).forEach(([k,n])=>n.classList.toggle("hidden",k!==name));window.scrollTo({top:0,behavior:"smooth"})}
  function formatDuration(s){const m=Math.floor(s/60),r=s%60;return m?`${m}分${String(r).padStart(2,"0")}秒`:`${r}秒`}
  function formatDate(iso){const d=new Date(iso);return `${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
  function questionsForSource(scope){if(scope==="first")return QUESTIONS.filter(q=>q.source==="小4前期");if(scope==="summer")return QUESTIONS.filter(q=>q.source==="夏期講習");return QUESTIONS}
  function questionsForScope(scope){if(scope==="first")return questionsForSource(scope).filter(q=>state.selectedUnits.includes(q.unit));if(scope==="summer")return questionsForSource(scope).filter(q=>state.selectedSummerRegions.includes(q.region));return questionsForSource(scope)}
  function scopeLabel(){if(state.scope==="first")return state.selectedUnits.length===ALL_UNITS.length?"小4前期・全単元":`小4前期・単元${state.selectedUnits.join("・")}`;if(state.scope==="summer")return state.selectedSummerRegions.length===SUMMER_REGIONS.length?"夏期講習・全地域":`夏期講習・${state.selectedSummerRegions.join("・")}`;return SCOPE_LABELS[state.scope]}
  function recordType(item){return item.quizType==="written"?"written":"choice"}
  function validateQuestions(){const ids=new Set();QUESTIONS.forEach((q,i)=>{if(!q.id||ids.has(q.id))throw new Error(`問題IDが不正です: ${i+1}`);ids.add(q.id);if(!q.question||!q.region||!q.source||!Array.isArray(q.choices)||q.choices.length!==6)throw new Error(`問題データが不正です: ${q.id}`);if(new Set(q.choices).size!==6||q.answerIndex<0||q.answerIndex>5||q.choices[q.answerIndex]!==q.answer||q.choices.filter(x=>x===q.answer).length!==1)throw new Error(`選択肢が不正です: ${q.id}`);if(q.source==="小4前期"&&(!Number.isInteger(q.unit)||q.unit<1||q.unit>17))throw new Error(`単元番号が不正です: ${q.id}`)})}
  function renderControls(){
    document.querySelectorAll("[data-quiz-type]").forEach(b=>{const on=b.dataset.quizType===state.quizType;b.classList.toggle("selected",on);b.setAttribute("aria-pressed",String(on))});
    document.querySelectorAll("[data-scope]").forEach(b=>{const on=b.dataset.scope===state.scope;b.classList.toggle("selected",on);b.setAttribute("aria-pressed",String(on))});
    Object.keys(SCOPE_LABELS).forEach(scope=>{const n=document.querySelector(`[data-scope-count="${scope}"]`);if(n)n.textContent=`${questionsForSource(scope).length}問`});
    $("unit-selector").classList.toggle("hidden",state.scope!=="first");$("summer-region-selector").classList.toggle("hidden",state.scope!=="summer");renderUnitOptions();renderSummerRegionOptions();const total=questionsForScope(state.scope).length;
    $("question-total").textContent=total;$("all-question-label").textContent=`${total}問すべて`;$("written-all-question-label").textContent=`${total}問すべて`;
    $("choice-challenge-options").classList.toggle("hidden",state.quizType!=="choice");$("written-challenge-options").classList.toggle("hidden",state.quizType!=="written");
    document.querySelectorAll("[data-question-count]").forEach(b=>{const n=b.dataset.questionCount;b.disabled=total===0||(n!=="all"&&total<Number(n))});document.querySelectorAll("[data-written-count]").forEach(b=>{const n=b.dataset.writtenCount;b.disabled=total===0||(n!=="all"&&total<Number(n))});
  }
  function renderUnitOptions(){const c=$("unit-options");c.replaceChildren();UNIT_META.forEach(item=>{const b=document.createElement("button"),on=state.selectedUnits.includes(item.unit),count=questionsForSource("first").filter(q=>q.unit===item.unit).length;b.type="button";b.className=`unit-button${on?" selected":""}`;b.dataset.unit=String(item.unit);b.setAttribute("aria-pressed",String(on));b.innerHTML=`<strong>単元${item.unit}</strong><span>${item.name}</span><small>${count}問</small>`;b.addEventListener("click",()=>toggleUnit(item.unit));c.append(b)});$("unit-selection-summary").textContent=`${state.selectedUnits.length}単元・${questionsForScope("first").length}問`}
  function setUnits(units){state.selectedUnits=[...new Set(units)].filter(x=>ALL_UNITS.includes(x)).sort((a,b)=>a-b);settings.selectedUnits=[...state.selectedUnits];saveSettings();renderControls()}
  function toggleUnit(unit){setUnits(state.selectedUnits.includes(unit)?state.selectedUnits.filter(x=>x!==unit):[...state.selectedUnits,unit])}
  function renderSummerRegionOptions(){const c=$("summer-region-options");c.replaceChildren();SUMMER_REGIONS.forEach(region=>{const b=document.createElement("button"),on=state.selectedSummerRegions.includes(region),count=questionsForSource("summer").filter(q=>q.region===region).length;b.type="button";b.className=`unit-button${on?" selected":""}`;b.dataset.summerRegion=region;b.setAttribute("aria-pressed",String(on));b.innerHTML=`<strong>${region}</strong><span>${SUMMER_TITLES[region]}</span><small>${count}問</small>`;b.addEventListener("click",()=>toggleSummerRegion(region));c.append(b)});$("summer-region-selection-summary").textContent=`${state.selectedSummerRegions.length}地域・${questionsForScope("summer").length}問`}
  function setSummerRegions(regions){state.selectedSummerRegions=SUMMER_REGIONS.filter(x=>regions.includes(x));settings.selectedSummerRegions=[...state.selectedSummerRegions];saveSettings();renderControls()}
  function toggleSummerRegion(region){setSummerRegions(state.selectedSummerRegions.includes(region)?state.selectedSummerRegions.filter(x=>x!==region):[...state.selectedSummerRegions,region])}
  function selectScope(scope){if(!SCOPE_LABELS[scope])return;state.scope=scope;settings.lastScope=scope;saveSettings();renderControls()}
  function selectQuizType(type){if(!TYPE_LABELS[type])return;state.quizType=type;settings.lastQuizType=type;saveSettings();renderControls()}
  function renderHistoryList(id,items,type){const c=$(id);c.replaceChildren();if(!items.length){c.innerHTML='<div class="empty">まだ記録はありません</div>';return}items.slice().reverse().slice(0,20).forEach(item=>{const row=document.createElement("div"),scope=item.scopeLabel?`・${item.scopeLabel}`:"",result=type==="written"?`○${item.correctCount??item.score??0}・△${item.partialCount??0}・×${item.wrongCount??Math.max(0,item.total-(item.score??0))}`:`${item.score}/${item.total}点（${item.rate}%）`;row.className="history-row";row.innerHTML=`<span>${formatDate(item.completedAt)}${scope}</span><strong>${result}</strong><span class="time">${formatDuration(item.durationSeconds)}</span>`;c.append(row)})}
  function masteryCounts(mastery){const units=ALL_UNITS.map(u=>unitRecord(mastery,u)),summer=SUMMER_REGIONS.map(r=>summerRecord(mastery,r));return{choice:units.filter(x=>x.choiceMastered).length,written:units.filter(x=>x.writtenMastered).length,summerChoice:summer.filter(x=>x.choiceMastered).length,summerWritten:summer.filter(x=>x.writtenMastered).length}}
  function currentRank(mastery){const c=masteryCounts(mastery);if(c.choice===17&&c.written===17&&c.summerChoice===7&&c.summerWritten===7)return{name:"真・社会マスター",emblem:"🔥",count:24,final:true};return[...RANKS].reverse().find(x=>c.choice>=x.count)}
  function nextRank(mastery){const c=masteryCounts(mastery),next=RANKS.find(x=>x.count>c.choice);if(next)return`次の「${next.name}」まで、前期4択であと${next.count-c.choice}単元`;if(c.written<17)return`最高位「真・社会マスター」まで、前期記述であと${17-c.written}単元`;if(c.summerChoice<7)return`最高位「真・社会マスター」まで、夏期4択であと${7-c.summerChoice}地域`;if(c.summerWritten<7)return`最高位「真・社会マスター」まで、夏期記述であと${7-c.summerWritten}地域`;return"全ランク制覇"}
  function showUnitMastery(unit,mastery=loadMastery()){const meta=UNIT_META.find(x=>x.unit===unit),r=unitRecord(mastery,unit),title=UNIT_TITLES[unit],earned=r.choiceMastered?(r.writtenMastered?`極・${title}`:title):"称号未獲得",pending=r.writtenPending?"｜記述は親の承認待ち":"",choice=r.choiceTotal?`${r.choiceBest}／${r.choiceTotal}・最高${r.choiceBestRate??Math.round(r.choiceBest/r.choiceTotal*100)}％`:"未挑戦",written=r.writtenTotal?`${r.writtenBest}／${r.writtenTotal}・最高${r.writtenBestRate??Math.round(r.writtenBest/r.writtenTotal*100)}％`:"未挑戦";$("unit-mastery-detail").innerHTML=`<strong>単元${unit} ${meta?.name||""}</strong><br>${earned}${pending}｜4択 ${choice}｜記述○ ${written}`}
  function showSummerMastery(region,mastery=loadMastery()){const r=summerRecord(mastery,region),title=SUMMER_TITLES[region],earned=r.choiceMastered?(r.writtenMastered?`極・${title}`:title):"称号未獲得",pending=r.writtenPending?"｜記述は親の承認待ち":"",choice=r.choiceTotal?`${r.choiceBest}／${r.choiceTotal}・最高${r.choiceBestRate??Math.round(r.choiceBest/r.choiceTotal*100)}％`:"未挑戦",written=r.writtenTotal?`${r.writtenBest}／${r.writtenTotal}・最高${r.writtenBestRate??Math.round(r.writtenBest/r.writtenTotal*100)}％`:"未挑戦";$("unit-mastery-detail").innerHTML=`<strong>夏期講習 ${region}</strong><br>${earned}${pending}｜4択 ${choice}｜記述○ ${written}`}
  function showSummerOverallMastery(mastery=loadMastery()){const c=masteryCounts(mastery),choiceDone=c.summerChoice===7,writtenDone=c.summerWritten===7,title=choiceDone?(writtenDone?"極・七地方の覇者":"七地方の覇者"):"称号未獲得",next=!choiceDone?`4択 あと${7-c.summerChoice}地域`:!writtenDone?`記述 あと${7-c.summerWritten}地域`:"夏期講習 完全制覇";$("unit-mastery-detail").innerHTML=`<strong>夏期講習・7地域総合</strong><br>${title}｜4択 ${c.summerChoice}／7｜記述 ${c.summerWritten}／7｜${next}`}
  function renderSummerOverallIcon(){const grid=$("summer-mastery-grid");if(!grid)return;grid.querySelector?.(".summer-overall-icon")?.remove();const mastery=loadMastery(),c=masteryCounts(mastery),choiceDone=c.summerChoice===7,writtenDone=c.summerWritten===7,b=document.createElement("button");b.type="button";b.className=`mastery-unit summer-overall-icon${choiceDone?" choice-mastered":""}${choiceDone&&writtenDone?" full-mastered":""}`;b.innerHTML='<span aria-hidden="true">👑</span><strong>7地域</strong>';b.title=choiceDone?(writtenDone?"極・七地方の覇者":"七地方の覇者"):`七地方の覇者まであと${7-c.summerChoice}地域`;b.setAttribute("aria-label",b.title);b.addEventListener("click",()=>showSummerOverallMastery(mastery));grid.append(b)}
  function renderRankCard(){const mastery=loadMastery(),c=masteryCounts(mastery),rank=currentRank(mastery);$("current-rank").textContent=rank.name;$("rank-emblem").textContent=rank.emblem;$("rank-progress").textContent=rank.final?"前期17単元・夏期7地域 完全制覇":"日本地理 攻略ランク";$("choice-mastery-count").textContent=`前期4択 ${c.choice}／17`;$("written-mastery-count").textContent=`前期記述 ${c.written}／17`;$("summer-choice-mastery-count").textContent=`夏期4択 ${c.summerChoice}／7`;$("summer-written-mastery-count").textContent=`夏期記述 ${c.summerWritten}／7`;$("next-rank").textContent=nextRank(mastery);const grid=$("unit-mastery-grid");grid.replaceChildren();ALL_UNITS.forEach(unit=>{const r=unitRecord(mastery,unit),b=document.createElement("button");b.type="button";b.className=`mastery-unit${r.choiceMastered?" choice-mastered":""}${r.choiceMastered&&r.writtenMastered?" full-mastered":""}`;b.textContent=String(unit);b.title=`単元${unit} ${UNIT_TITLES[unit]}`;b.setAttribute("aria-label",`単元${unit} ${r.choiceMastered?(r.writtenMastered?"4択と記述を制覇":"4択を制覇"):"未制覇"}`);b.addEventListener("click",()=>showUnitMastery(unit,mastery));grid.append(b)});const summerGrid=$("summer-mastery-grid");summerGrid.replaceChildren();SUMMER_REGIONS.forEach(region=>{const r=summerRecord(mastery,region),b=document.createElement("button");b.type="button";b.className=`mastery-unit${r.choiceMastered?" choice-mastered":""}${r.choiceMastered&&r.writtenMastered?" full-mastered":""}`;b.textContent=region;b.setAttribute("aria-label",`${region} ${r.choiceMastered?(r.writtenMastered?"4択と記述を制覇":"4択を制覇"):"未制覇"}`);b.addEventListener("click",()=>showSummerMastery(region,mastery));summerGrid.append(b)});const recent=[...ALL_UNITS.flatMap(unit=>{const r=unitRecord(mastery,unit);if(r.fullMasteredAt)return[{at:r.fullMasteredAt,title:`極・${UNIT_TITLES[unit]}`}];if(r.choiceMasteredAt)return[{at:r.choiceMasteredAt,title:UNIT_TITLES[unit]}];return[]}),...SUMMER_REGIONS.flatMap(region=>{const r=summerRecord(mastery,region);if(r.fullMasteredAt)return[{at:r.fullMasteredAt,title:`極・${SUMMER_TITLES[region]}`}];if(r.choiceMasteredAt)return[{at:r.choiceMasteredAt,title:SUMMER_TITLES[region]}];return[]})].sort((a,b)=>String(b.at).localeCompare(String(a.at)))[0];$("recent-title").textContent=recent?`最近獲得した称号：「${recent.title}」`:"最初の攻略称号を手に入れよう！"}
  function applyParentApprovalIndicators(){renderSummerOverallIcon();const mastery=loadMastery(),unitButtons=[...$("unit-mastery-grid").children],summerButtons=[...$("summer-mastery-grid").children];let pending=0;ALL_UNITS.forEach((unit,i)=>{const on=Boolean(unitRecord(mastery,unit).writtenPending);unitButtons[i]?.classList.toggle("pending-approval",on);if(on)pending++});SUMMER_REGIONS.forEach((region,i)=>{const on=Boolean(summerRecord(mastery,region).writtenPending);summerButtons[i]?.classList.toggle("pending-approval",on);if(on)pending++});$("parent-review-summary").textContent=`親の承認待ち ${pending}件`}
  function renderHome(){renderControls();renderRankCard();applyParentApprovalIndicators();const p=loadProgress(),todayResults=p.history.filter(x=>x.dateKey===localDateKey()),today=todayResults[todayResults.length-1];$("today-status").classList.toggle("done",Boolean(today));$("today-status").textContent=today?`今日の社会学習：完了（${TYPE_LABELS[recordType(today)]}）`:"今日の社会学習：まだやっていません";renderHistoryList("history-list",p.history.filter(x=>recordType(x)==="choice"),"choice");renderHistoryList("written-history-list",p.history.filter(x=>recordType(x)==="written"),"written")}
  function makeRound(q){const answer=q.answer,distractors=shuffle(q.choices.filter(choice=>choice!==answer)).slice(0,3),choices=shuffle([answer,...distractors]);return{...q,choices,correctIndex:choices.indexOf(answer),answer}}
  function startMain(requested,type=state.quizType){const pool=questionsForScope(state.scope),size=requested==="all"?pool.length:Number(requested);if(!Number.isInteger(size)||size<1||!pool.length)return;let masteryTarget=null;if(requested==="all"&&state.scope==="first"&&state.selectedUnits.length===1)masteryTarget={kind:"unit",key:state.selectedUnits[0]};if(requested==="all"&&state.scope==="summer"&&state.selectedSummerRegions.length===1)masteryTarget={kind:"summer",key:state.selectedSummerRegions[0]};Object.assign(state,{sessionMode:"main",quizType:type,deck:shuffle(pool).slice(0,Math.min(size,pool.length)).map(makeRound),index:0,score:0,answers:[],startedAt:Date.now(),mainResult:null,masteryTarget,achievementEvents:[]});showScreen("quiz");renderQuestion()}
  function startReview(){if(!state.mainResult?.wrong.length)return;Object.assign(state,{sessionMode:"review",deck:state.mainResult.wrong.map(x=>QUESTIONS.find(q=>q.id===x.id)).filter(Boolean).map(makeRound),index:0,score:0,answers:[],startedAt:Date.now(),masteryTarget:null,achievementEvents:[]});showScreen("quiz");renderQuestion()}
  function questionTag(q){return q.source==="小4前期"?`前期・単元${q.unit}・${q.region}`:`夏期・${q.region}`}
  function renderQuestion(){const q=state.deck[state.index],written=state.quizType==="written";$("region").textContent=state.sessionMode==="review"?`復習・${questionTag(q)}`:questionTag(q);$("progress").textContent=`${state.index+1} / ${state.deck.length}`;$("progress-bar").style.width=`${state.index/state.deck.length*100}%`;$("question").textContent=q.question;$("feedback").className="feedback hidden";$("next-button").classList.add("hidden");$("choices").classList.toggle("hidden",written);$("written-panel").classList.toggle("hidden",!written);if(written){$("written-instruction").classList.remove("hidden");$("reveal-answer-button").classList.remove("hidden");$("written-answer").classList.add("hidden");$("self-grade-buttons").classList.add("hidden")}else{const c=$("choices");c.replaceChildren();q.choices.forEach((choice,i)=>{const b=document.createElement("button");b.className="choice";b.textContent=choice;b.addEventListener("click",()=>answerChoice(i));c.append(b)})}}
  function revealWrittenAnswer(){const q=state.deck[state.index];$("written-instruction").classList.add("hidden");$("reveal-answer-button").classList.add("hidden");$("written-answer").textContent=`正解：${q.answer}`;$("written-answer").classList.remove("hidden");$("self-grade-buttons").classList.remove("hidden")}
  function showNext(){$("next-button").textContent=state.index===state.deck.length-1?"結果を見る":"次の問題";$("next-button").classList.remove("hidden")}
  function answerChoice(i){const q=state.deck[state.index],correct=i===q.correctIndex;playSound(correct);[...$("choices").children].forEach((b,n)=>{b.disabled=true;if(n===q.correctIndex)b.classList.add("correct");if(n===i&&!correct)b.classList.add("wrong")});if(correct)state.score++;state.answers.push({id:q.id,question:q.question,selected:q.choices[i],correct:q.answer,isCorrect:correct});const f=$("feedback");f.className=`feedback ${correct?"correct":"wrong"}`;f.textContent=correct?"正解！":`残念！ 正解は「${q.answer}」`;showNext()}
  function answerWritten(grade){if(!["correct","partial","wrong"].includes(grade))return;const q=state.deck[state.index];if(grade==="correct")state.score++;playSound(grade==="correct");state.answers.push({id:q.id,question:q.question,correct:q.answer,grade,isCorrect:grade==="correct"});$("self-grade-buttons").classList.add("hidden");const f=$("feedback");f.className=`feedback ${grade==="correct"?"correct":grade==="partial"?"partial":"wrong"}`;f.textContent=grade==="correct"?"○ 漢字まで正解！":grade==="partial"?"△ 答えは分かった。漢字・表記を確認しよう。":"× 次は思い出せるようにしよう。";showNext()}
  function next(){state.index++;state.index<state.deck.length?renderQuestion():finish()}
  function updateMastery(result){if(!state.masteryTarget||state.sessionMode!=="main")return;const mastery=loadMastery(),beforeRank=currentRank(mastery),beforeCounts=masteryCounts(mastery),{kind,key}=state.masteryTarget,isSummer=kind==="summer",old=isSummer?summerRecord(mastery,key):unitRecord(mastery,key),r={...old},title=isSummer?SUMMER_TITLES[key]:UNIT_TITLES[key],place=isSummer?key:`単元${key}`,now=new Date().toISOString(),perfect=result.score===result.total,rate=Math.round(result.score/result.total*100);if(state.quizType==="written"){r.writtenAttempts=(r.writtenAttempts||0)+1;r.writtenBestRate=Math.max(r.writtenBestRate||0,rate);if(result.score>(r.writtenBest||0)||result.score===(r.writtenBest||0)&&result.total<(r.writtenTotal||Infinity)){r.writtenBest=result.score;r.writtenTotal=result.total}if(perfect&&!r.writtenMastered){r.writtenPending=true;r.writtenPendingAt=now;r.writtenPendingScore=result.score;r.writtenPendingTotal=result.total;state.achievementEvents.push({label:"親の承認待ち",title:`${place}の記述全問○を親に確認してもらおう`})}}else{r.choiceAttempts=(r.choiceAttempts||0)+1;r.choiceBestRate=Math.max(r.choiceBestRate||0,rate);if(result.score>(r.choiceBest||0)||result.score===(r.choiceBest||0)&&result.total<(r.choiceTotal||Infinity)){r.choiceBest=result.score;r.choiceTotal=result.total}if(perfect&&!r.choiceMastered){r.choiceMastered=true;r.choiceMasteredAt=now;state.achievementEvents.push({label:"称号獲得！",title:`「${title}」`})}}if(isSummer)mastery.summerRegions[key]=r;else mastery.units[String(key)]=r;const afterCounts=masteryCounts(mastery);if(beforeCounts.summerChoice<7&&afterCounts.summerChoice===7&&!mastery.summerChoiceCompleteAt){mastery.summerChoiceCompleteAt=now;state.achievementEvents.push({label:"夏期講習7地域制覇！",title:"「七地方の覇者」"})}saveMastery(mastery);const afterRank=currentRank(mastery);if(afterRank.name!==beforeRank.name)state.achievementEvents.push({label:"ランクアップ！",title:`「${afterRank.name}」`})}
  function finish(){const duration=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),written=state.quizType==="written",partial=written?state.answers.filter(x=>x.grade==="partial").length:0,wrong=written?state.answers.filter(x=>x.grade!=="correct"):state.answers.filter(x=>!x.isCorrect),wrongCount=written?state.answers.filter(x=>x.grade==="wrong").length:wrong.length,result={score:state.score,total:state.deck.length,rate:Math.round(state.score/state.deck.length*100),durationSeconds:duration,partialCount:partial,wrongCount,wrong};if(state.sessionMode==="main"){state.mainResult=result;const p=loadProgress();p.history.push({completedAt:new Date().toISOString(),dateKey:localDateKey(),quizType:state.quizType,score:result.score,total:result.total,rate:result.rate,correctCount:result.score,partialCount:partial,wrongCount,durationSeconds:duration,scope:state.scope,scopeLabel:scopeLabel(),units:state.scope==="first"?[...state.selectedUnits]:undefined,summerRegions:state.scope==="summer"?[...state.selectedSummerRegions]:undefined});p.history=p.history.slice(-100);saveProgress(p);updateMastery(result)}renderResult(result,state.sessionMode);showScreen("result")}
  function renderResult(result,mode){const written=state.quizType==="written";$("result-title").textContent=mode==="review"?"復習完了！":written?"記述練習完了！":result.rate===100?"全問正解！":result.rate>=80?"よくできました！":"もう一度がんばろう！";$("result-score").textContent=written?`○ ${result.score}`:`${result.score} / ${result.total}`;$("result-rate").textContent=written?`${result.total}問を自己判定`:`正答率 ${result.rate}%`;$("written-result-summary").classList.toggle("hidden",!written);$("written-result-summary").textContent=written?`○ ${result.score}問　△ ${result.partialCount}問　× ${result.wrongCount}問`:"";$("result-time").textContent=`所要時間 ${formatDuration(result.durationSeconds)}`;const achievement=$("achievement-banner");achievement.classList.toggle("hidden",!state.achievementEvents.length);achievement.replaceChildren();state.achievementEvents.forEach(event=>{const p=document.createElement("p"),strong=document.createElement("strong");p.textContent=event.label;strong.textContent=event.title;achievement.append(p,strong)});const s=$("wrong-section");s.replaceChildren();if(result.wrong.length){const h=document.createElement("h2");h.textContent=written?`確認する問題（${result.wrong.length}問）`:`間違えた問題（${result.wrong.length}問）`;s.append(h);result.wrong.forEach(item=>{const d=document.createElement("div");d.className="wrong-item";d.innerHTML=written?`<strong>${item.question}</strong><p class="wrong-answer">判定：${item.grade==="partial"?"△ 漢字・表記ミス":"× 思い出せなかった"}</p><p class="correct-answer">正解：${item.correct}</p>`:`<strong>${item.question}</strong><p class="wrong-answer">あなたの答え：${item.selected}</p><p class="correct-answer">正解：${item.correct}</p>`;s.append(d)})}else s.innerHTML='<p class="empty">確認が必要な問題はありません。</p>';const review=$("review-button"),can=mode==="main"&&result.wrong.length>0;review.classList.toggle("hidden",!can);if(can)review.textContent=written?`△・×の${result.wrong.length}問をもう一度`:`間違えた${result.wrong.length}問をもう一度`}
  function goHome(){renderHome();showScreen("home")}
  function toggleRankDetails(){const details=$("rank-details"),open=details.classList.contains("hidden");details.classList.toggle("hidden",!open);$("rank-toggle").setAttribute("aria-expanded",String(open));$("rank-toggle-icon").textContent=open?"▲":"▼"}
  function hashParentPin(pin){let h=2166136261;for(const ch of `social-master-parent:${pin}`){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")}
  function askNewParentPin(){const pin=prompt("親用の4桁の暗証番号を設定してください。");if(pin===null)return null;if(!/^\d{4}$/.test(pin)){alert("暗証番号は数字4桁で設定してください。");return null}const again=prompt("確認のため、同じ暗証番号をもう一度入力してください。");if(again!==pin){alert("暗証番号が一致しません。");return null}return pin}
  function verifyParentPin(mastery=loadMastery()){const pin=prompt("親用の4桁の暗証番号を入力してください。");if(pin===null)return false;if(hashParentPin(pin)!==mastery.parentPinHash){alert("暗証番号が違います。");return false}return true}
  function renderSettings(){const mastery=loadMastery(),configured=Boolean(mastery.parentPinHash),status=$("parent-pin-status"),button=$("set-parent-pin"),review=$("settings-parent-review");if(!status||!button||!review)return;status.textContent=configured?"設定済み":"未設定";status.classList.toggle("configured",configured);button.textContent=configured?"暗証番号を変更する":"暗証番号を設定する";review.textContent=`記述の承認管理（待ち ${parentEntries(mastery).filter(x=>x.record.writtenPending).length}件）`}
  function openSettings(){$("settings-status").textContent="";renderSettings();$("settings-panel").classList.remove("hidden")}
  function closeSettings(){$("settings-panel")?.classList.add("hidden")}
  function setOrChangeParentPin(){const mastery=loadMastery(),changing=Boolean(mastery.parentPinHash);if(changing&&!verifyParentPin(mastery))return;const pin=askNewParentPin();if(!pin)return;mastery.parentPinHash=hashParentPin(pin);recordParentAction(mastery,changing?"pin-change":"pin-set",{kind:"parent",key:"pin"});saveMastery(mastery);$("settings-status").textContent=changing?"親用暗証番号を変更しました。":"親用暗証番号を設定しました。";renderSettings()}
  function parentEntries(mastery){return[...ALL_UNITS.map(unit=>({kind:"unit",key:unit,label:`前期 単元${unit} ${UNIT_META.find(x=>x.unit===unit)?.name||""}`,title:UNIT_TITLES[unit],record:unitRecord(mastery,unit)})),...SUMMER_REGIONS.map(region=>({kind:"summer",key:region,label:`夏期講習 ${region}`,title:SUMMER_TITLES[region],record:summerRecord(mastery,region)}))].filter(x=>x.record.writtenPending||x.record.writtenMastered)}
  function saveParentRecord(mastery,item,record){if(item.kind==="summer")mastery.summerRegions[item.key]=record;else mastery.units[String(item.key)]=record}
  function recordParentAction(mastery,action,item){mastery.parentActions=Array.isArray(mastery.parentActions)?mastery.parentActions:[];mastery.parentActions.push({action,kind:item.kind,key:item.key,at:new Date().toISOString()});mastery.parentActions=mastery.parentActions.slice(-100)}
  function approveWritten(item){const mastery=loadMastery(),beforeRank=currentRank(mastery),r={...(item.kind==="summer"?summerRecord(mastery,item.key):unitRecord(mastery,item.key))},now=new Date().toISOString();r.writtenPending=false;r.writtenMastered=true;r.writtenMasteredAt=now;if(r.choiceMastered)r.fullMasteredAt=now;saveParentRecord(mastery,item,r);recordParentAction(mastery,"approve",item);const c=masteryCounts(mastery);let message=`${item.label}を承認しました。`;if(r.choiceMastered)message+=` 「極・${item.title}」を獲得しました。`;if(c.summerChoice===7&&c.summerWritten===7&&!mastery.summerFullCompleteAt){mastery.summerFullCompleteAt=now;message+=' 「極・七地方の覇者」を獲得しました。'}saveMastery(mastery);const afterRank=currentRank(mastery);if(afterRank.name!==beforeRank.name)message+=` ランクが「${afterRank.name}」になりました。`;$("parent-panel-status").textContent=message;renderRankCard();applyParentApprovalIndicators();renderParentReviewList()}
  function rejectWritten(item){const mastery=loadMastery(),r={...(item.kind==="summer"?summerRecord(mastery,item.key):unitRecord(mastery,item.key))};r.writtenPending=false;delete r.writtenPendingAt;delete r.writtenPendingScore;delete r.writtenPendingTotal;saveParentRecord(mastery,item,r);recordParentAction(mastery,"reject",item);saveMastery(mastery);$("parent-panel-status").textContent=`${item.label}の承認待ちを却下しました。`;renderRankCard();applyParentApprovalIndicators();renderParentReviewList()}
  function revokeWritten(item){if(!confirm(`${item.label}の記述制覇を取り消しますか？`))return;const mastery=loadMastery(),r={...(item.kind==="summer"?summerRecord(mastery,item.key):unitRecord(mastery,item.key))};r.writtenMastered=false;r.writtenPending=false;delete r.writtenMasteredAt;delete r.fullMasteredAt;if(item.kind==="summer")delete mastery.summerFullCompleteAt;saveParentRecord(mastery,item,r);recordParentAction(mastery,"revoke",item);saveMastery(mastery);$("parent-panel-status").textContent=`${item.label}の記述制覇を取り消しました。`;renderRankCard();applyParentApprovalIndicators();renderParentReviewList()}
  function renderParentReviewList(){const mastery=loadMastery(),items=parentEntries(mastery),list=$("parent-review-list");list.replaceChildren();if(!items.length){list.innerHTML='<div class="empty">承認待ち・承認済みの記述制覇はありません。</div>';return}items.forEach(item=>{const box=document.createElement("div"),actions=document.createElement("div");box.className="parent-review-item";actions.className="parent-review-actions";box.innerHTML=`<strong>${item.label}</strong><span>${item.record.writtenPending?`承認待ち：○ ${item.record.writtenPendingScore||item.record.writtenBest}／${item.record.writtenPendingTotal||item.record.writtenTotal}`:"承認済み"}</span>`;if(item.record.writtenPending){const approve=document.createElement("button"),reject=document.createElement("button");approve.className="approve";approve.textContent="承認する";reject.className="reject";reject.textContent="却下する";approve.addEventListener("click",()=>approveWritten(item));reject.addEventListener("click",()=>rejectWritten(item));actions.append(approve,reject)}if(item.record.writtenMastered){const revoke=document.createElement("button");revoke.className="revoke";revoke.textContent="承認を取り消す";revoke.addEventListener("click",()=>revokeWritten(item));actions.append(revoke)}box.append(actions);list.append(box)})}
  function openParentPanel(){const mastery=loadMastery();if(!mastery.parentPinHash){const pin=askNewParentPin();if(!pin)return;mastery.parentPinHash=hashParentPin(pin);recordParentAction(mastery,"pin-set",{kind:"parent",key:"pin"});saveMastery(mastery);renderSettings()}else if(!verifyParentPin(mastery))return;closeSettings();$("parent-panel-status").textContent="";renderParentReviewList();$("parent-panel").classList.remove("hidden")}
  function closeParentPanel(){$("parent-panel").classList.add("hidden")}
  function changeParentPin(){const pin=askNewParentPin();if(!pin)return;const mastery=loadMastery();mastery.parentPinHash=hashParentPin(pin);recordParentAction(mastery,"pin-change",{kind:"parent",key:"pin"});saveMastery(mastery);$("parent-panel-status").textContent="親用暗証番号を変更しました。";renderSettings()}
  function backupFilename(){const d=new Date();return `社会マスター_バックアップ_${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}.json`}
  function setBackupStatus(message,error=false){["backup-status","settings-backup-status"].forEach(id=>{const n=$(id);n.textContent=message;n.classList.toggle("error",error)})}
  function exportSave(){try{const payload={app:"社会マスター",formatVersion:1,exportedAt:new Date().toISOString(),progress:loadProgress(),settings:loadSettings(),mastery:loadMastery()},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=backupFilename();document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setBackupStatus("バックアップを保存しました。端末のダウンロードまたはファイルをご確認ください。")}catch{setBackupStatus("バックアップを保存できませんでした。",true)}}
  function validateBackup(data){if(!data||data.app!=="社会マスター"||data.formatVersion!==1||!data.progress||!Array.isArray(data.progress.history)||!data.settings||typeof data.settings!=="object")throw new Error("invalid");return data}
  async function importSave(file){if(!file)return;try{const data=validateBackup(JSON.parse(await file.text()));if(!confirm(`バックアップの記録（${data.progress.history.length}件）・設定・称号データで、現在のセーブデータを上書きしますか？`))return;saveProgress({version:1,history:data.progress.history.slice(-100)});localStorage.setItem(SETTINGS_KEY,JSON.stringify(data.settings));saveMastery(data.mastery&&data.mastery.units?data.mastery:emptyMastery());setBackupStatus("バックアップを読み込みました。設定を反映するため画面を更新します。");setTimeout(()=>location.reload(),500)}catch{setBackupStatus("このファイルは社会マスターの正しいバックアップではありません。",true)}finally{$("import-save-file").value=""}}
  document.querySelectorAll("[data-quiz-type]").forEach(b=>b.addEventListener("click",()=>selectQuizType(b.dataset.quizType)));document.querySelectorAll("[data-scope]").forEach(b=>b.addEventListener("click",()=>selectScope(b.dataset.scope)));document.querySelectorAll("[data-question-count]").forEach(b=>b.addEventListener("click",()=>startMain(b.dataset.questionCount,"choice")));document.querySelectorAll("[data-written-count]").forEach(b=>b.addEventListener("click",()=>startMain(b.dataset.writtenCount,"written")));document.querySelectorAll("[data-self-grade]").forEach(b=>b.addEventListener("click",()=>answerWritten(b.dataset.selfGrade)));
  $("rank-toggle").addEventListener("click",toggleRankDetails);$("parent-review-button").addEventListener("click",openParentPanel);$("close-parent-panel").addEventListener("click",closeParentPanel);$("change-parent-pin").addEventListener("click",changeParentPin);$("select-all-units").addEventListener("click",()=>setUnits(ALL_UNITS));$("clear-units").addEventListener("click",()=>setUnits([]));$("select-all-summer-regions").addEventListener("click",()=>setSummerRegions(SUMMER_REGIONS));$("clear-summer-regions").addEventListener("click",()=>setSummerRegions([]));$("reveal-answer-button").addEventListener("click",revealWrittenAnswer);$("next-button").addEventListener("click",next);$("review-button").addEventListener("click",startReview);$("home-button").addEventListener("click",goHome);$("quit-button").addEventListener("click",()=>{if(confirm("クイズを途中でやめてTOPへ戻りますか？"))goHome()});$("clear-history-button").addEventListener("click",()=>{if(confirm("4択と記述の記録をすべて消しますか？")){saveProgress({version:1,history:[]});renderHome()}});$("sound-enabled").addEventListener("change",e=>{settings.soundEnabled=e.target.checked;saveSettings();renderSoundSettings()});$("sound-volume").addEventListener("input",e=>{settings.soundVolume=Number(e.target.value)/100;saveSettings();renderSoundSettings()});
  $("export-save-button").addEventListener("click",exportSave);$("import-save-button").addEventListener("click",()=>$("import-save-file").click());$("import-save-file").addEventListener("change",e=>importSave(e.target.files?.[0]));
  $("open-settings-button")?.addEventListener("click",openSettings);$("close-settings-button")?.addEventListener("click",closeSettings);$("set-parent-pin")?.addEventListener("click",setOrChangeParentPin);$("settings-parent-review")?.addEventListener("click",openParentPanel);$("settings-export-save-button")?.addEventListener("click",exportSave);$("settings-import-save-button")?.addEventListener("click",()=>$("import-save-file").click());
  validateQuestions();renderSoundSettings();renderHome();
})();
