(function(){
  "use strict";
  const QUESTIONS=window.GEOGRAPHY_QUESTIONS||[];
  const STORAGE_KEY="social-quiz-progress-v1",SETTINGS_KEY="social-quiz-settings-v1";
  const SCOPE_LABELS={first:"小4前期",summer:"夏期講習",all:"全範囲"},TYPE_LABELS={choice:"4択",written:"記述"};
  const UNIT_META=[...new Map(QUESTIONS.filter(q=>q.source==="小4前期").map(q=>[q.unit,{unit:q.unit,name:q.unitName||`単元${q.unit}`}])).values()].sort((a,b)=>a.unit-b.unit),ALL_UNITS=UNIT_META.map(x=>x.unit);
  const screens={home:document.getElementById("home-screen"),quiz:document.getElementById("quiz-screen"),result:document.getElementById("result-screen")},$=id=>document.getElementById(id);
  const state={sessionMode:"main",quizType:"choice",scope:"first",selectedUnits:[],deck:[],index:0,score:0,answers:[],startedAt:0,mainResult:null};
  function shuffle(values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function localDateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
  function loadProgress(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));return v&&Array.isArray(v.history)?v:{version:1,history:[]}}catch{return{version:1,history:[]}}}
  function saveProgress(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
  function loadSettings(){try{const v=JSON.parse(localStorage.getItem(SETTINGS_KEY));const selectedUnits=Array.isArray(v?.selectedUnits)?[...new Set(v.selectedUnits.filter(x=>ALL_UNITS.includes(x)))].sort((a,b)=>a-b):[...ALL_UNITS];return{soundEnabled:v?.soundEnabled!==false,soundVolume:Number.isFinite(v?.soundVolume)?Math.max(0,Math.min(1,v.soundVolume)):0.7,lastScope:SCOPE_LABELS[v?.lastScope]?v.lastScope:"first",lastQuizType:TYPE_LABELS[v?.lastQuizType]?v.lastQuizType:"choice",selectedUnits}}catch{return{soundEnabled:true,soundVolume:0.7,lastScope:"first",lastQuizType:"choice",selectedUnits:[...ALL_UNITS]}}}
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  const settings=loadSettings();state.scope=settings.lastScope;state.quizType=settings.lastQuizType;state.selectedUnits=[...settings.selectedUnits];
  const AUDIO_REVISION="20260814-v8",sounds={correct:new Audio(`./se-correct.mp3?v=${AUDIO_REVISION}`),wrong:new Audio(`./se-wrong.mp3?v=${AUDIO_REVISION}`)};Object.values(sounds).forEach(x=>x.preload="auto");
  function playSound(correct){if(!settings.soundEnabled||settings.soundVolume<=0)return;const x=correct?sounds.correct:sounds.wrong;x.pause();x.currentTime=0;x.volume=settings.soundVolume;const p=x.play();if(p?.catch)p.catch(()=>{})}
  function renderSoundSettings(){$("sound-enabled").checked=settings.soundEnabled;$("sound-enabled").nextElementSibling.textContent=settings.soundEnabled?"効果音 ON":"効果音 OFF";$("sound-volume").value=Math.round(settings.soundVolume*100);$("sound-volume-value").textContent=`${Math.round(settings.soundVolume*100)}%`}
  function showScreen(name){Object.entries(screens).forEach(([k,n])=>n.classList.toggle("hidden",k!==name));window.scrollTo({top:0,behavior:"smooth"})}
  function formatDuration(s){const m=Math.floor(s/60),r=s%60;return m?`${m}分${String(r).padStart(2,"0")}秒`:`${r}秒`}
  function formatDate(iso){const d=new Date(iso);return `${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
  function questionsForSource(scope){if(scope==="first")return QUESTIONS.filter(q=>q.source==="小4前期");if(scope==="summer")return QUESTIONS.filter(q=>q.source==="夏期講習");return QUESTIONS}
  function questionsForScope(scope){return scope==="first"?questionsForSource(scope).filter(q=>state.selectedUnits.includes(q.unit)):questionsForSource(scope)}
  function scopeLabel(){if(state.scope!=="first")return SCOPE_LABELS[state.scope];return state.selectedUnits.length===ALL_UNITS.length?"小4前期・全単元":`小4前期・単元${state.selectedUnits.join("・")}`}
  function recordType(item){return item.quizType==="written"?"written":"choice"}
  function validateQuestions(){const ids=new Set();QUESTIONS.forEach((q,i)=>{if(!q.id||ids.has(q.id))throw new Error(`問題IDが不正です: ${i+1}`);ids.add(q.id);if(!q.question||!q.region||!q.source||!Array.isArray(q.choices)||q.choices.length!==4)throw new Error(`問題データが不正です: ${q.id}`);if(new Set(q.choices).size!==4||q.answerIndex<0||q.answerIndex>3||q.choices[q.answerIndex]!==q.answer)throw new Error(`選択肢が不正です: ${q.id}`);if(q.source==="小4前期"&&(!Number.isInteger(q.unit)||q.unit<1||q.unit>17))throw new Error(`単元番号が不正です: ${q.id}`)})}
  function renderControls(){
    document.querySelectorAll("[data-quiz-type]").forEach(b=>{const on=b.dataset.quizType===state.quizType;b.classList.toggle("selected",on);b.setAttribute("aria-pressed",String(on))});
    document.querySelectorAll("[data-scope]").forEach(b=>{const on=b.dataset.scope===state.scope;b.classList.toggle("selected",on);b.setAttribute("aria-pressed",String(on))});
    Object.keys(SCOPE_LABELS).forEach(scope=>{const n=document.querySelector(`[data-scope-count="${scope}"]`);if(n)n.textContent=`${questionsForSource(scope).length}問`});
    $("unit-selector").classList.toggle("hidden",state.scope!=="first");renderUnitOptions();const total=questionsForScope(state.scope).length;
    $("question-total").textContent=total;$("all-question-label").textContent=`${total}問すべて`;$("written-all-question-label").textContent=`${total}問すべて`;
    $("choice-challenge-options").classList.toggle("hidden",state.quizType!=="choice");$("written-challenge-options").classList.toggle("hidden",state.quizType!=="written");
    document.querySelectorAll("[data-question-count]").forEach(b=>{const n=b.dataset.questionCount;b.disabled=total===0||(n!=="all"&&total<Number(n))});document.querySelectorAll("[data-written-count]").forEach(b=>{const n=b.dataset.writtenCount;b.disabled=total===0||(n!=="all"&&total<Number(n))});
  }
  function renderUnitOptions(){const c=$("unit-options");c.replaceChildren();UNIT_META.forEach(item=>{const b=document.createElement("button"),on=state.selectedUnits.includes(item.unit),count=questionsForSource("first").filter(q=>q.unit===item.unit).length;b.type="button";b.className=`unit-button${on?" selected":""}`;b.dataset.unit=String(item.unit);b.setAttribute("aria-pressed",String(on));b.innerHTML=`<strong>単元${item.unit}</strong><span>${item.name}</span><small>${count}問</small>`;b.addEventListener("click",()=>toggleUnit(item.unit));c.append(b)});$("unit-selection-summary").textContent=`${state.selectedUnits.length}単元・${questionsForScope("first").length}問`}
  function setUnits(units){state.selectedUnits=[...new Set(units)].filter(x=>ALL_UNITS.includes(x)).sort((a,b)=>a-b);settings.selectedUnits=[...state.selectedUnits];saveSettings();renderControls()}
  function toggleUnit(unit){setUnits(state.selectedUnits.includes(unit)?state.selectedUnits.filter(x=>x!==unit):[...state.selectedUnits,unit])}
  function selectScope(scope){if(!SCOPE_LABELS[scope])return;state.scope=scope;settings.lastScope=scope;saveSettings();renderControls()}
  function selectQuizType(type){if(!TYPE_LABELS[type])return;state.quizType=type;settings.lastQuizType=type;saveSettings();renderControls()}
  function renderHistoryList(id,items,type){const c=$(id);c.replaceChildren();if(!items.length){c.innerHTML='<div class="empty">まだ記録はありません</div>';return}items.slice().reverse().slice(0,20).forEach(item=>{const row=document.createElement("div"),scope=item.scopeLabel?`・${item.scopeLabel}`:"",result=type==="written"?`○${item.correctCount??item.score??0}・△${item.partialCount??0}・×${item.wrongCount??Math.max(0,item.total-(item.score??0))}`:`${item.score}/${item.total}点（${item.rate}%）`;row.className="history-row";row.innerHTML=`<span>${formatDate(item.completedAt)}${scope}</span><strong>${result}</strong><span class="time">${formatDuration(item.durationSeconds)}</span>`;c.append(row)})}
  function renderHome(){renderControls();const p=loadProgress(),todayResults=p.history.filter(x=>x.dateKey===localDateKey()),today=todayResults[todayResults.length-1];$("today-status").classList.toggle("done",Boolean(today));$("today-status").textContent=today?`今日の社会学習：完了（${TYPE_LABELS[recordType(today)]}）`:"今日の社会学習：まだやっていません";renderHistoryList("history-list",p.history.filter(x=>recordType(x)==="choice"),"choice");renderHistoryList("written-history-list",p.history.filter(x=>recordType(x)==="written"),"written")}
  function makeRound(q){const answer=q.choices[q.answerIndex],choices=shuffle(q.choices);return{...q,choices,correctIndex:choices.indexOf(answer),answer}}
  function startMain(requested,type=state.quizType){const pool=questionsForScope(state.scope),size=requested==="all"?pool.length:Number(requested);if(!Number.isInteger(size)||size<1||!pool.length)return;Object.assign(state,{sessionMode:"main",quizType:type,deck:shuffle(pool).slice(0,Math.min(size,pool.length)).map(makeRound),index:0,score:0,answers:[],startedAt:Date.now(),mainResult:null});showScreen("quiz");renderQuestion()}
  function startReview(){if(!state.mainResult?.wrong.length)return;Object.assign(state,{sessionMode:"review",deck:state.mainResult.wrong.map(x=>QUESTIONS.find(q=>q.id===x.id)).filter(Boolean).map(makeRound),index:0,score:0,answers:[],startedAt:Date.now()});showScreen("quiz");renderQuestion()}
  function questionTag(q){return q.source==="小4前期"?`前期・単元${q.unit}・${q.region}`:`夏期・${q.region}`}
  function renderQuestion(){const q=state.deck[state.index],written=state.quizType==="written";$("region").textContent=state.sessionMode==="review"?`復習・${questionTag(q)}`:questionTag(q);$("progress").textContent=`${state.index+1} / ${state.deck.length}`;$("progress-bar").style.width=`${state.index/state.deck.length*100}%`;$("question").textContent=q.question;$("feedback").className="feedback hidden";$("next-button").classList.add("hidden");$("choices").classList.toggle("hidden",written);$("written-panel").classList.toggle("hidden",!written);if(written){$("written-instruction").classList.remove("hidden");$("reveal-answer-button").classList.remove("hidden");$("written-answer").classList.add("hidden");$("self-grade-buttons").classList.add("hidden")}else{const c=$("choices");c.replaceChildren();q.choices.forEach((choice,i)=>{const b=document.createElement("button");b.className="choice";b.textContent=choice;b.addEventListener("click",()=>answerChoice(i));c.append(b)})}}
  function revealWrittenAnswer(){const q=state.deck[state.index];$("written-instruction").classList.add("hidden");$("reveal-answer-button").classList.add("hidden");$("written-answer").textContent=`正解：${q.answer}`;$("written-answer").classList.remove("hidden");$("self-grade-buttons").classList.remove("hidden")}
  function showNext(){$("next-button").textContent=state.index===state.deck.length-1?"結果を見る":"次の問題";$("next-button").classList.remove("hidden")}
  function answerChoice(i){const q=state.deck[state.index],correct=i===q.correctIndex;playSound(correct);[...$("choices").children].forEach((b,n)=>{b.disabled=true;if(n===q.correctIndex)b.classList.add("correct");if(n===i&&!correct)b.classList.add("wrong")});if(correct)state.score++;state.answers.push({id:q.id,question:q.question,selected:q.choices[i],correct:q.answer,isCorrect:correct});const f=$("feedback");f.className=`feedback ${correct?"correct":"wrong"}`;f.textContent=correct?"正解！":`残念！ 正解は「${q.answer}」`;showNext()}
  function answerWritten(grade){if(!["correct","partial","wrong"].includes(grade))return;const q=state.deck[state.index];if(grade==="correct")state.score++;playSound(grade==="correct");state.answers.push({id:q.id,question:q.question,correct:q.answer,grade,isCorrect:grade==="correct"});$("self-grade-buttons").classList.add("hidden");const f=$("feedback");f.className=`feedback ${grade==="correct"?"correct":grade==="partial"?"partial":"wrong"}`;f.textContent=grade==="correct"?"○ 漢字まで正解！":grade==="partial"?"△ 答えは分かった。漢字・表記を確認しよう。":"× 次は思い出せるようにしよう。";showNext()}
  function next(){state.index++;state.index<state.deck.length?renderQuestion():finish()}
  function finish(){const duration=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),written=state.quizType==="written",partial=written?state.answers.filter(x=>x.grade==="partial").length:0,wrong=written?state.answers.filter(x=>x.grade!=="correct"):state.answers.filter(x=>!x.isCorrect),wrongCount=written?state.answers.filter(x=>x.grade==="wrong").length:wrong.length,result={score:state.score,total:state.deck.length,rate:Math.round(state.score/state.deck.length*100),durationSeconds:duration,partialCount:partial,wrongCount,wrong};if(state.sessionMode==="main"){state.mainResult=result;const p=loadProgress();p.history.push({completedAt:new Date().toISOString(),dateKey:localDateKey(),quizType:state.quizType,score:result.score,total:result.total,rate:result.rate,correctCount:result.score,partialCount:partial,wrongCount,durationSeconds:duration,scope:state.scope,scopeLabel:scopeLabel(),units:state.scope==="first"?[...state.selectedUnits]:undefined});p.history=p.history.slice(-100);saveProgress(p)}renderResult(result,state.sessionMode);showScreen("result")}
  function renderResult(result,mode){const written=state.quizType==="written";$("result-title").textContent=mode==="review"?"復習完了！":written?"記述練習完了！":result.rate===100?"全問正解！":result.rate>=80?"よくできました！":"もう一度がんばろう！";$("result-score").textContent=written?`○ ${result.score}`:`${result.score} / ${result.total}`;$("result-rate").textContent=written?`${result.total}問を自己判定`:`正答率 ${result.rate}%`;$("written-result-summary").classList.toggle("hidden",!written);$("written-result-summary").textContent=written?`○ ${result.score}問　△ ${result.partialCount}問　× ${result.wrongCount}問`:"";$("result-time").textContent=`所要時間 ${formatDuration(result.durationSeconds)}`;const s=$("wrong-section");s.replaceChildren();if(result.wrong.length){const h=document.createElement("h2");h.textContent=written?`確認する問題（${result.wrong.length}問）`:`間違えた問題（${result.wrong.length}問）`;s.append(h);result.wrong.forEach(item=>{const d=document.createElement("div");d.className="wrong-item";d.innerHTML=written?`<strong>${item.question}</strong><p class="wrong-answer">判定：${item.grade==="partial"?"△ 漢字・表記ミス":"× 思い出せなかった"}</p><p class="correct-answer">正解：${item.correct}</p>`:`<strong>${item.question}</strong><p class="wrong-answer">あなたの答え：${item.selected}</p><p class="correct-answer">正解：${item.correct}</p>`;s.append(d)})}else s.innerHTML='<p class="empty">確認が必要な問題はありません。</p>';const review=$("review-button"),can=mode==="main"&&result.wrong.length>0;review.classList.toggle("hidden",!can);if(can)review.textContent=written?`△・×の${result.wrong.length}問をもう一度`:`間違えた${result.wrong.length}問をもう一度`}
  function goHome(){renderHome();showScreen("home")}
  document.querySelectorAll("[data-quiz-type]").forEach(b=>b.addEventListener("click",()=>selectQuizType(b.dataset.quizType)));document.querySelectorAll("[data-scope]").forEach(b=>b.addEventListener("click",()=>selectScope(b.dataset.scope)));document.querySelectorAll("[data-question-count]").forEach(b=>b.addEventListener("click",()=>startMain(b.dataset.questionCount,"choice")));document.querySelectorAll("[data-written-count]").forEach(b=>b.addEventListener("click",()=>startMain(b.dataset.writtenCount,"written")));document.querySelectorAll("[data-self-grade]").forEach(b=>b.addEventListener("click",()=>answerWritten(b.dataset.selfGrade)));
  $("select-all-units").addEventListener("click",()=>setUnits(ALL_UNITS));$("clear-units").addEventListener("click",()=>setUnits([]));$("reveal-answer-button").addEventListener("click",revealWrittenAnswer);$("next-button").addEventListener("click",next);$("review-button").addEventListener("click",startReview);$("home-button").addEventListener("click",goHome);$("quit-button").addEventListener("click",()=>{if(confirm("クイズを途中でやめてTOPへ戻りますか？"))goHome()});$("clear-history-button").addEventListener("click",()=>{if(confirm("4択と記述の記録をすべて消しますか？")){saveProgress({version:1,history:[]});renderHome()}});$("sound-enabled").addEventListener("change",e=>{settings.soundEnabled=e.target.checked;saveSettings();renderSoundSettings()});$("sound-volume").addEventListener("input",e=>{settings.soundVolume=Number(e.target.value)/100;saveSettings();renderSoundSettings()});
  validateQuestions();renderSoundSettings();renderHome();
})();
